/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PerformanceReports;

import business.Business;
import business.UserAccount.UserAccount;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import javax.swing.JPanel;

/**
 *
 * @author anushasenthilnathan
 */
public class PerformanceRating1 extends javax.swing.JPanel {

    /**
     * Creates new form PerformanceRating
     */
    JPanel userProcessContainer;
    Business business;
    public PerformanceRating1(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        assignTextBox();
    }
    
    private ArrayList<UserAccount> findTop3Employees() {
        HashMap<UserAccount, Integer> empCount = new HashMap<>();
        for(WorkRequest request : this.business.getAppLogEmpOrganization().getWorkQueue().getWorkRequestList()){
            if(!empCount.containsKey(request.getReceiver())){
               empCount.put(request.getReceiver(), 1);
            }
            else{
              empCount.put(request.getReceiver(), empCount.get(request.getReceiver())+1);  
            }   
        }
        ArrayList<UserAccount> empList = this.business.getAppLogEmpOrganization().getUserAccountDirectory().getUserAccountList();
        Collections.sort(empList, new UserMapComparator(empCount));
    
    return empList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top1TF = new javax.swing.JTextField();
        top2TF = new javax.swing.JTextField();
        top3TF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(top1TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 140, 40));

        top2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                top2TFActionPerformed(evt);
            }
        });
        add(top2TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, 150, 40));
        add(top3TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 570, 140, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PerformanceReports/rank1.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PerformanceReports/rank2.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, 130));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PerformanceReports/rank3.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 130, 180));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PerformanceReports/emp1.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 220, 260));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PerformanceReports/woman.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, 270));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PerformanceReports/emp2.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, 260));

        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PerformanceReports/left-arrow-in-circular-button-black-symbol.png"))); // NOI18N
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        btnBack.setOpaque(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PerformanceReports/Background.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 1100));

        jLabel7.setText("jLabel7");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void top2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top2TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_top2TFActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField top1TF;
    private javax.swing.JTextField top2TF;
    private javax.swing.JTextField top3TF;
    // End of variables declaration//GEN-END:variables

    private void assignTextBox() {
        this.top1TF.setText("Not Assigned");
        this.top2TF.setText("Not Assigned");
        this.top3TF.setText("Not Assigned");
        int counter=0;
        for(int i=0; i<findTop3Employees().size();i++){
            if(i==0)
                this.top1TF.setText(findTop3Employees().get(i).getEmployee().getName());
            else if(i==1)
                this.top2TF.setText(findTop3Employees().get(i).getEmployee().getName());
            else if(i==2)
                this.top3TF.setText(findTop3Employees().get(i).getEmployee().getName());
            counter+=1;
            if(counter==3)
                break;
        }
    }
}
