/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.OGLogEmpRole;

import business.Business;
import business.Enterprise.AppLogBusiness.Pkg;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.OGLogEmpWorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sathya
 */
public class DeliveryJpanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryJpanel
     */
    JPanel userProcessContainer;
    Business business;
    UserAccount account;
    Organization organization;
    OGLogEmpWorkRequest request;
    Pkg pkg;
    public DeliveryJpanel(JPanel userProcessContainer, UserAccount account, Organization organization, Business business, OGLogEmpWorkRequest request) {
        initComponents();
                this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.business = business;
        this.request = request;
        this.pkg = this.request.getPkg();
        this.rNameTf.setText(this.pkg.getRecv_name());
        this.rContacttf.setText(this.pkg.getRecv_cno());
        this.rAddressTf.setText(this.pkg.getRecv_address());
        this.shipTypeTf.setText(this.pkg.getShipType());
        this.idTextField.setText(String.valueOf(this.pkg.getPackage_id()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        shipTypeTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rNameTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rAddressTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rContacttf = new javax.swing.JTextField();
        deliverBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgTa = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText(" ON-GROUND LOGISTICS EMPLOYEE WORK RESPONSIBILITY (DELIVERY)");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 15, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" PACKAGE ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 30));

        idTextField.setEditable(false);
        idTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 160, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SHIP TYPE");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 169, 170, 30));

        shipTypeTf.setEditable(false);
        shipTypeTf.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        add(shipTypeTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 160, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RECEIVER NAME");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, 30));

        rNameTf.setEditable(false);
        rNameTf.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        add(rNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 160, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RECEIVER ADDRESS");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, 30));

        rAddressTf.setEditable(false);
        rAddressTf.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        add(rAddressTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 160, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RECEIVER CONTACT");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 200, 30));

        rContacttf.setEditable(false);
        rContacttf.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        add(rContacttf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 160, 30));

        deliverBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        deliverBtn.setText("Deliver");
        deliverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverBtnActionPerformed(evt);
            }
        });
        add(deliverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 117, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/OGLogEmpRole/Delivery.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 350, 270));

        msgTa.setColumns(20);
        msgTa.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        msgTa.setRows(5);
        msgTa.setText("Leave a Message .....");
        jScrollPane1.setViewportView(msgTa);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PerformanceReports/left-arrow-in-circular-button-black-symbol.png"))); // NOI18N
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        btnBack.setOpaque(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/OGLogEmpRole/Background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1500, 1100));
    }// </editor-fold>//GEN-END:initComponents

    private void deliverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverBtnActionPerformed
        // TODO add your handling code here:
        this.request.setResult(this.msgTa.getText());
        this.request.getPkg().setStatus(10);       this.request.setStatus("Completed");
        this.request.setResolveDate(new Date());
        this.request.getPrevCargoReq().getPrevAssignEmpReq().setResult("Package has been delivered");
        JOptionPane.showMessageDialog(this, "Package Delivered");
    }//GEN-LAST:event_deliverBtnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton deliverBtn;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea msgTa;
    private javax.swing.JTextField rAddressTf;
    private javax.swing.JTextField rContacttf;
    private javax.swing.JTextField rNameTf;
    private javax.swing.JTextField shipTypeTf;
    // End of variables declaration//GEN-END:variables
}
