/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.OGAdminRole;

import business.Business;
import business.CargoEnterprise.AirlinesSchedule;
import business.Enterprise.AppLogBusiness.Pkg;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.CargoWorkRequest;
import business.WorkQueue.OGLogEmpWorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sathya
 */
public class ReceivePackageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReceivePackageJPanel
     */
        JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Business business;
    String dateString;
    public ReceivePackageJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.business = business;
        populateCmbBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        dateCmbBox = new javax.swing.JComboBox<>();
        processBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("ON-GROUND LOGISTICS WORK ADMIN RESPONSIBILITY");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 28, -1, -1));

        dateCmbBox.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        dateCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dateCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateCmbBoxActionPerformed(evt);
            }
        });
        add(dateCmbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 123, 117, -1));

        processBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        processBtn.setText("PROCESS");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });
        add(processBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/OGAdminRole/ADMIN.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 280, 240));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RECEIVE ALL PACKAGES AND GENERATE WORK REQUESTS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 186, 550, 36));

        btnBack2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PerformanceReports/left-arrow-in-circular-button-black-symbol.png"))); // NOI18N
        btnBack2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        btnBack2.setOpaque(true);
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/OGAdminRole/Background.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1500, 820));
    }// </editor-fold>//GEN-END:initComponents

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        // TODO add your handling code here:
        this.dateString = (String)this.dateCmbBox.getSelectedItem();
        generateWorkRequest();
        JOptionPane.showMessageDialog(this, "Work Request Generated");
    }//GEN-LAST:event_processBtnActionPerformed

    private void dateCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateCmbBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateCmbBoxActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JComboBox<String> dateCmbBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton processBtn;
    // End of variables declaration//GEN-END:variables

    private void populateCmbBox() {
        dateCmbBox.removeAllItems();
        for(AirlinesSchedule schedule : this.business.getAirScheduleList()){
            dateCmbBox.addItem(schedule.getDate());
        }
    }
    
    private void generateWorkRequest(){
        CargoWorkRequest req = null;
        boolean status;
        for (Map.Entry<CargoWorkRequest, Boolean> set :
             this.business.getCer().getCargoRequestList().entrySet()) {
             req = set.getKey();
             status = set.getValue();
             if(status==false  && req.getPkg().getSchedule().getDate().equals(this.dateString)){                 
                OGLogEmpWorkRequest ogLogEmpWorkRequest = new OGLogEmpWorkRequest();
                ogLogEmpWorkRequest.setPrevCargoReq(req);
                ogLogEmpWorkRequest.setMessage(req.getPkg().getShipType());
                ogLogEmpWorkRequest.setRequestDate(new Date());
                ogLogEmpWorkRequest.setSender(account);
                ogLogEmpWorkRequest.setStatus("Sent");
                req.getPkg().setStatus(8);
                ogLogEmpWorkRequest.setPkg(req.getPkg());
                this.business.getOGLogEmpOrganization().getWorkQueue().getWorkRequestList().add(ogLogEmpWorkRequest);
                this.account.getWorkQueue().getWorkRequestList().add(ogLogEmpWorkRequest);
                this.business.getCer().getCargoRequestList().put(req, Boolean.TRUE);
        }
    }
    }
}
