/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.BusinessAdmin;

import business.Business;
import business.Enterprise.AppLogBusiness.DailyPricing;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ErrorHelper.ErrorHelper;
import java.awt.CardLayout;

/**
 *
 * @author Sathya
 */
public class ManagePricingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePricingJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Business business;
    public ManagePricingJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.business = business;
        config();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        expprice = new javax.swing.JLabel();
        expPriceTextField = new javax.swing.JTextField();
        priorityPrice = new javax.swing.JLabel();
        priorityPriceTextField = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("DAILY PRICING");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 300, -1));

        expprice.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        expprice.setForeground(new java.awt.Color(255, 255, 255));
        expprice.setText("EXPRESS PRICE");
        add(expprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 160, -1));
        add(expPriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 200, -1));

        priorityPrice.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        priorityPrice.setForeground(new java.awt.Color(255, 255, 255));
        priorityPrice.setText("PRIORITY PRICE");
        add(priorityPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 150, -1));
        add(priorityPriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 200, -1));

        date.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("TODAY's DATE");
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 160, -1));
        add(dateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 200, -1));

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton1.setText("GENERATE PRICING");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/BusinessAdmin/BusinessAdmin.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 750, 320));

        btnBack2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PerformanceReports/left-arrow-in-circular-button-black-symbol.png"))); // NOI18N
        btnBack2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        btnBack2.setOpaque(true);
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/BusinessAdmin/Background.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 1110));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      try{
      DailyPricing dp = new DailyPricing();
      dp.setDate(new Date());
      String today = dp.getDate();
      float expPriceF = Float.parseFloat(this.expPriceTextField.getText());
      //String expPrice = String.valueOf(expPriceF);
      float priPriceF  = Float.parseFloat(this.priorityPriceTextField.getText());
      //String priPrice = String.valueOf(priPrice);    
      dp.setExpressPrice(expPriceF);
      dp.setPriorityPrice(priPriceF);
      this.business.getDailyPricingList().setDailyPricing(today, dp);
      JOptionPane.showMessageDialog(this, "Prices set successfully");
      config();
      }
      catch(Exception e){
          e.printStackTrace();
          ErrorHelper.showError("No other characters expected other than 0-9");
      }


        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack2;
    private javax.swing.JLabel date;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField expPriceTextField;
    private javax.swing.JLabel expprice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel priorityPrice;
    private javax.swing.JTextField priorityPriceTextField;
    // End of variables declaration//GEN-END:variables

    private void config() {
      String today = new SimpleDateFormat("dd/MM/YYYY").format(new Date());
      DailyPricing dp = this.business.getDailyPricingList().getDailyPricingList(today);
      this.dateTextField.setText(today);
      if(dp==null){
          this.expPriceTextField.setText("Not Configured");
          this.priorityPriceTextField.setText("Not Configured");
      }
      else{
         this.expPriceTextField.setText(String.valueOf(dp.getExpressPrice()));
         this.priorityPriceTextField.setText(String.valueOf(dp.getPriorityPrice()));
      }
    }
}
