/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Customer;

import business.Business;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import ErrorHelper.ErrorHelper;
import business.Enterprise.AppLogBusiness.DailyPricing;
import business.Enterprise.AppLogBusiness.Pkg;
import business.WorkQueue.AssignEmpWorkRequest;
import business.WorkQueue.WorkRequest;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Sathya
 */
public class CustomerQuoteJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerQuoteJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Business business;
    float weight;
    Pkg pkg;
    public CustomerQuoteJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.business = business;
        populateCmbBox();
        this.proceedBtn.setVisible(false);
        this.typeCmbBox.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        weightTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        expGstTextField = new javax.swing.JTextField();
        expTotalChargesTextField = new javax.swing.JTextField();
        expScTextField = new javax.swing.JTextField();
        priGstTextField = new javax.swing.JTextField();
        priTcTextField = new javax.swing.JTextField();
        priScTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        getQuoteBtn = new javax.swing.JButton();
        typeCmbBox = new javax.swing.JComboBox();
        proceedBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ESTIMATED BILLING");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 260, 40));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WEIGHT IN Kg's");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 157, -1));

        weightTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        add(weightTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 200, 40));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SHIPPING CHARGES ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GST");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 107, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TOTAL CHARGES");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 170, -1));

        expGstTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        add(expGstTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 170, 40));

        expTotalChargesTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        add(expTotalChargesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 170, 40));

        expScTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        expScTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expScTextFieldActionPerformed(evt);
            }
        });
        add(expScTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 170, 40));

        priGstTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        add(priGstTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 170, 40));

        priTcTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        add(priTcTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 170, 40));

        priScTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        add(priScTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 170, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PRIORITY");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 100, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EXPRESS");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 90, -1));

        getQuoteBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        getQuoteBtn.setText("GENERATE");
        getQuoteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getQuoteBtnActionPerformed(evt);
            }
        });
        add(getQuoteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 160, 40));

        typeCmbBox.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        add(typeCmbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 130, 40));

        proceedBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        proceedBtn.setText("Proceed ");
        proceedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedBtnActionPerformed(evt);
            }
        });
        add(proceedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 110, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Customer/Box.jpeg"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 370, 240));

        btnBack2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PerformanceReports/left-arrow-in-circular-button-black-symbol.png"))); // NOI18N
        btnBack2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        btnBack2.setOpaque(true);
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Customer/Background.jpg"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 1100));

        jLabel9.setText("jLabel9");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 150, 160));

        jLabel10.setText("jLabel10");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, -1, -1));

        jLabel12.setText("jLabel12");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 250, 290));
    }// </editor-fold>//GEN-END:initComponents

    private void getQuoteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getQuoteBtnActionPerformed
        // TODO add your handling code here:
        try{
            float weight = (Float.parseFloat(this.weightTextField.getText()));
            String today = new SimpleDateFormat("dd/MM/YYYY").format(new Date());
            DailyPricing dp = this.business.getDailyPricingList().getDailyPricingList(today);
            if(dp!=null){
            float expSc = dp.getExpressPrice()* weight;
            float expGst = expSc*10/100;
            float expTc = expGst + expSc;
            
            float priSc = dp.getPriorityPrice()*weight;
            float priGst = priSc*10/100;
            float priTc = priGst + priSc;
            
            expScTextField.setText(String.valueOf(expSc));
            expGstTextField.setText(String.valueOf(expGst));
            expTotalChargesTextField.setText(String.valueOf(expTc));
            
            priScTextField.setText(String.valueOf(priSc));
            priGstTextField.setText(String.valueOf(priGst));
            priTcTextField.setText(String.valueOf(priTc));
            
            JOptionPane.showMessageDialog(this, "Prices are updated as of "+today);
            this.weight = weight;
            this.typeCmbBox.setVisible(true);
            this.proceedBtn.setVisible(true);
            }
            else
                ErrorHelper.showError("Prices Not Yet Configured. Please reach out to Admin");
        }
        catch(Exception e){
            e.printStackTrace();
            ErrorHelper.showError("Weight Cannot contain any other characters other than 0-9");
        }
    }//GEN-LAST:event_getQuoteBtnActionPerformed

    private void proceedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedBtnActionPerformed
        // TODO add your handling code here:
        //0-> express 1->priority
        int index = this.typeCmbBox.getSelectedIndex();
        if(index==0){
           this.pkg = this.business.getPackageList().createPackage(account, "Express");
           String today = new SimpleDateFormat("dd/MM/YYYY").format(new Date());
           DailyPricing dp = this.business.getDailyPricingList().getDailyPricingList(today);
           if(pkg!=null){   
               pkg.setWeight(this.weight);
               pkg.setShippingPrice(this.weight*dp.getExpressPrice());
               pkg.setGst(pkg.getShippingPrice()*10/100);
               pkg.setNetPrice();
               pkg.setStatus(0);
           }
           else{
               ErrorHelper.showError("Something went wrong");
               return;
           }
        }
        else if(index==1){
           this.pkg = this.business.getPackageList().createPackage(account, "Priority");
           String today = new SimpleDateFormat("dd/MM/YYYY").format(new Date());
           DailyPricing dp = this.business.getDailyPricingList().getDailyPricingList(today);
           if(pkg!=null){   
               pkg.setWeight(this.weight);
               pkg.setShippingPrice(this.weight*dp.getPriorityPrice());
               pkg.setGst(pkg.getShippingPrice()*10/100);
               pkg.setNetPrice();
           }
           else{
               ErrorHelper.showError("Something went wrong");
               return;
           }
        }
        boolean isExist = checkAnyOpenReqExist();
        if(!isExist){
        AssignEmpWorkRequest assignEmpWorkRequest = new AssignEmpWorkRequest();
        assignEmpWorkRequest.setPkg(pkg);
        assignEmpWorkRequest.setSender(account);
        assignEmpWorkRequest.setStatus("Sent");
        assignEmpWorkRequest.setMessage("Executive Assignment Request");
        assignEmpWorkRequest.setRequestDate(new Date());
        this.account.getWorkQueue().getWorkRequestList().add(assignEmpWorkRequest);
        this.business.getAppLogEmpOrganization().getWorkQueue().getWorkRequestList().add(assignEmpWorkRequest);
        JOptionPane.showMessageDialog(this, "A request has been sent to the concerned team\nYou will be assigned an Logistic Support Person very soon\nHope you have a good experience");
        }
        else{
            ErrorHelper.showError("One of our representatives will look into your\nrequest. Thanks for your patience");
        }
    }//GEN-LAST:event_proceedBtnActionPerformed

    private void expScTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expScTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expScTextFieldActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack2;
    private javax.swing.JTextField expGstTextField;
    private javax.swing.JTextField expScTextField;
    private javax.swing.JTextField expTotalChargesTextField;
    private javax.swing.JButton getQuoteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField priGstTextField;
    private javax.swing.JTextField priScTextField;
    private javax.swing.JTextField priTcTextField;
    private javax.swing.JButton proceedBtn;
    private javax.swing.JComboBox typeCmbBox;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables

    private void populateCmbBox() {
        this.typeCmbBox.removeAllItems();
        this.typeCmbBox.addItem("Express");
        this.typeCmbBox.addItem("Priority");
    }

    private boolean checkAnyOpenReqExist() {
        for(WorkRequest workRequest : this.account.getWorkQueue().getWorkRequestList()){
            if(workRequest.getStatus().equalsIgnoreCase("Pending") ||
               workRequest.getStatus().equalsIgnoreCase("Processing")||
               workRequest.getStatus().equalsIgnoreCase("Sent"))
                return true;
        }
        return false;
    }
}
