/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Customer;

import ErrorHelper.ErrorHelper;
import business.Business;
import business.Employee.Employee;
import business.Role.CustomerRole;
import business.Role.Role;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sathya
 */
public class CustomerSignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerSignUpJPanel
     */
    JPanel mainWorkArea;
    Business business;

    public CustomerSignUpJPanel(JPanel mainWorkArea, Business business) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        UserNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pwdTextField = new javax.swing.JTextField();
        signUpBtn = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CUSTOMER SIGN-UP");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 300, 26));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 79, 24));
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 174, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USER NAME");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 110, 24));
        add(UserNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 174, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 100, 24));
        add(pwdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 174, -1));

        signUpBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        signUpBtn.setText("SIGN UP");
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });
        add(signUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        btnBack2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PerformanceReports/left-arrow-in-circular-button-black-symbol.png"))); // NOI18N
        btnBack2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        btnBack2.setOpaque(true);
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Customer/Background.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 1500, 1150));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Customer/User.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 260, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        // TODO add your handling code here:
        String name = this.nameTextField.getText();
        String username = this.UserNameTextField.getText();
        String pwd = this.pwdTextField.getText();
        if (name.isBlank() || username.isBlank() || pwd.isBlank()) {
            ErrorHelper.showError("Name, UserName or Password Field is Empty");
        } else {
            if (validatePwd(pwd)) {
                if (this.business.getCustomerOrganization() == null) {
                    ErrorHelper.showError("Org not found");
                } else {
                    Employee emp = this.business.getCustomerOrganization().getEmployeeDirectory().createEmployee(name);
                    Role role = this.business.getCustomerOrganization().getSupportedRole().get(0);
                    UserAccount ua = this.business.getCustomerOrganization().getUserAccountDirectory().createUserAccount(username, pwd, emp, role);
                    JOptionPane.showMessageDialog(this, "User created Successfully");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Password must contain alteast 8 characters, one upper case\none lower case and one digit", "WARNING", JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_signUpBtnActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed

        mainWorkArea.remove(this);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_btnBack2ActionPerformed
    private boolean validatePwd(String pwd) {
        return pwd.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JButton btnBack2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField pwdTextField;
    private javax.swing.JButton signUpBtn;
    // End of variables declaration//GEN-END:variables
}
