/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Customer;

import business.Business;
import business.Enterprise.AppLogBusiness.Item;
import business.Enterprise.AppLogBusiness.Pkg;
import business.Enterprise.AppLogBusiness.sItemList;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ErrorHelper.ErrorHelper;
import business.WorkQueue.AssignEmpWorkRequest;
import business.WorkQueue.PackingRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Sathya
 */
public class ManageItemsPackageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageItemsPackageJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Business business;
    Pkg pkg;
    ArrayList<Item> tempItems;

    public ManageItemsPackageJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.business = business;
        populatePkgCB();
        populateItemsCB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pkgCmbBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        itemCmbBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsTbl = new javax.swing.JTable();
        removeBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        backBtn2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Package Items");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, 31));

        pkgCmbBox.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        pkgCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pkgCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pkgCmbBoxActionPerformed(evt);
            }
        });
        add(pkgCmbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 282, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Package");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Items");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 80, -1));

        itemCmbBox.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        itemCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(itemCmbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 282, -1));

        itemsTbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        itemsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Item"
            }
        ));
        jScrollPane1.setViewportView(itemsTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 125));

        removeBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBtn.setText("Push Request to Support Person");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));

        addBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        backBtn2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        backBtn2.setText("<< Back");
        backBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn2ActionPerformed(evt);
            }
        });
        add(backBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Customer/Background.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1510, 1100));
    }// </editor-fold>//GEN-END:initComponents

    private void pkgCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pkgCmbBoxActionPerformed
        // TODO add your handling code here:
        this.pkg = (Pkg) this.pkgCmbBox.getSelectedItem();
        if(this.pkg!=null){
        this.tempItems = this.pkg.getItemList().getItemList();
        poulateItemsTbl(this.pkg);
        }
    }//GEN-LAST:event_pkgCmbBoxActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) itemsTbl.getModel();
        int index  = this.itemsTbl.getSelectedRow();
        Item item = (Item)this.itemsTbl.getValueAt(index, 0);
        if(index==-1)
            ErrorHelper.showWarning("A row must be selected");
        else{
            this.tempItems.remove(item);
            poulateItemsTbl(this.pkg);
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        Item item = (Item)this.itemCmbBox.getSelectedItem();
        if(!this.tempItems.contains(item))
            this.tempItems.add(item);
        else
            ErrorHelper.showWarning("Item already added");
        poulateItemsTbl(pkg);
    }//GEN-LAST:event_addBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        boolean isExist = checkAnyOpenReqExist();
        if(!isExist){
        this.pkg.setStatus(2);
        AssignEmpWorkRequest assignEmpWorkRequest = new AssignEmpWorkRequest();
        assignEmpWorkRequest.setPkg(pkg);
        assignEmpWorkRequest.setSender(account);
        assignEmpWorkRequest.setStatus("Sent");
        assignEmpWorkRequest.setMessage("Packing request initiated");
        assignEmpWorkRequest.setRequestDate(new Date());
        this.account.getWorkQueue().getWorkRequestList().add(assignEmpWorkRequest);
        this.business.getAppLogEmpOrganization().getWorkQueue().getWorkRequestList().add(assignEmpWorkRequest);
        JOptionPane.showMessageDialog(this, "A request has been sent to the concerned team\nYou will be assigned an Logistic Support Person very soon\nHope you have a good experience");
        }
        else{
            ErrorHelper.showError("One of our representatives will look into your\nrequest. Thanks for your patience");
        }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void backBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn2ActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        ((CardLayout)this.userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backBtn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn2;
    private javax.swing.JComboBox itemCmbBox;
    private javax.swing.JTable itemsTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox pkgCmbBox;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables

    private void populatePkgCB() {
        System.out.println("called 1st");
        this.pkgCmbBox.removeAllItems();
        for (Pkg pkg : this.business.getPackageList().getPackageList()) {
            if (pkg.getCustomerUA().equals(this.account) && pkg.getStatus() == 1) {
                this.pkgCmbBox.addItem(pkg);
            }
        }
        this.pkg = (Pkg) this.pkgCmbBox.getSelectedItem();

    }

    private void populateItemsCB() {
        this.itemCmbBox.removeAllItems();
        for (Item item : sItemList.staticItemList) {
            this.itemCmbBox.addItem(item);
        }
    }

    private void poulateItemsTbl(Pkg pkg) {
        DefaultTableModel dtm = (DefaultTableModel) itemsTbl.getModel();
        dtm.setRowCount(0);
        if(this.tempItems!=null)
        for (Item item : this.tempItems) {
            Object[] obj = new Object[1];
            obj[0] = item;
            dtm.addRow(obj);
        }
    }

    private boolean checkAnyOpenReqExist() {
        for(WorkRequest workRequest : this.account.getWorkQueue().getWorkRequestList()){
            if(workRequest.getStatus().equalsIgnoreCase("Pending") ||
               workRequest.getStatus().equalsIgnoreCase("Processing")||
               workRequest.getStatus().equalsIgnoreCase("Sent"))
                return true;
        }
        return false;
    }
    
}
