/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PackagerRole;

import business.Business;
import business.WorkQueue.AssignEmpWorkRequest;
import business.WorkQueue.PackingRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sathya
 */
public class ProcessPackRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessPackRequestJPanel
     */
    JPanel userProcessContainer;
    PackingRequest request;
    Business business;
    public ProcessPackRequestJPanel(JPanel userProcessContainer, PackingRequest request, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnSubmit2 = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        txtResults = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("RESULT SUBMISSION");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 290, 50));

        btnSubmit2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSubmit2.setText("SUBMIT RESULT");
        btnSubmit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit2ActionPerformed(evt);
            }
        });
        add(btnSubmit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, -1, -1));

        lblResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblResult.setForeground(new java.awt.Color(255, 255, 255));
        lblResult.setText("RESULT:");
        add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));
        add(txtResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 294, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PackagerRole/result.jpeg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 550, -1));

        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PerformanceReports/left-arrow-in-circular-button-black-symbol.png"))); // NOI18N
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        btnBack.setOpaque(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/PackagerRole/Background.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1110));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit2ActionPerformed
        
        this.request.getPkg().setStatus(4);
        this.request.setResolveDate(new Date());
        this.request.getPrevReq().setResult((this.txtResults.getText()==null)?"No Comments":this.txtResults.getText());
        this.request.setStatus("Completed");
        JOptionPane.showMessageDialog(this, "Request Resolved");
        
    }//GEN-LAST:event_btnSubmit2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtResults;
    // End of variables declaration//GEN-END:variables
}
